---
- hosts: nishant-fedora-vm@192.168.0.102
  become: yes
  become_user: root
  tasks:
    - name: Execute remote script
      shell: /home/nishant-fedora-vm/nishant.sh
      register: result

    - debug:
        var: result

    - name: Install git
      dnf:
        name: git
        state: latest

    - name: Install nano
      dnf:
        name: nano
        state: latest

    - name: Install htop
      dnf:
        name: htop
        state: latest
